### ISSUE TITLE
Trouble with nested jsr packages...

### ISSUE THREAD

**Issue by raaymax** [denoland/deno-vite-plugin#15]
```
error during build:
[vite-plugin-pwa:build] Could not load jsr:@std/streams@^0.224.5 (imported by deno::TypeScript::https://jsr.io/@planigale/sse/0.2.3/deps.ts::/Users/raay/Library/Caches/deno/remote/https/jsr.io/1fbe815f78baf2095cdb6b95a5bfdaa23c06f117e2a35bcbdd4d5411a2848324): No such file or directory (os error 2): readfile 'jsr:@std/streams@^0.224.5'
    at Object.readFile (ext:deno_fs/30_fs.js:747:24)
    at readFile (ext:deno_node/_fs/_fs_readFile.ts:29:14)
    at ext:deno_node/_fs/_fs_readFile.ts:44:5
    at new Promise (<anonymous>)
    at Object.readFilePromise [as readFile] (ext:deno_node/_fs/_fs_readFile.ts:43:10)
    at Object.load (file:///Users/raay/Workspace/CodeCat/Quack/Chat/node_modules/.deno/vite@5.4.8/node_modules/vite/dist/node/chunks/dep-CDnG8rE7.js:65034:35)
    at async PluginDriver.hookFirstAndGetPlugin (file:///Users/raay/Workspace/CodeCat/Quack/Chat/node_modules/.deno/rollup@4.24.0/node_modules/rollup/dist/es/shared/node-entry.js:20630:28)
    at async file:///Users/raay/Workspace/CodeCat/Quack/Chat/node_modules/.deno/rollup@4.24.0/node_modules/rollup/dist/es/shared/node-entry.js:19750:33
    at async Queue.work (file:///Users/raay/Workspace/CodeCat/Quack/Chat/node_modules/.deno/rollup@4.24.0/node_modules/rollup/dist/es/shared/node-entry.js:20840:32)
```
in this case `jsr:@std/streams@^0.224.5` is used in `jsr:@planigale/sse@0.2.3` which is used by my project.

**Comment by inverted-capital** [comment]
that might have something to do with the ^ semver ranges - I think the deno vite plugin needs pinned packages.
