### ISSUE TITLE
Unable to resolve jsr dependencies when vendor: true in deno.json

### ISSUE THREAD

**Issue by bavoco** [denoland/deno-vite-plugin#18]
To reproduce:
- run `deno clean`
- create a deno.json
- run `deno add jsr:@std/encoding`
- create an index.html which imports index.ts which imports @std/encoding/base64
- add the plugin to your vite.config.ts
- run `deno run -A npm:vite`
- the following error will appear:
```text
[vite] Internal server error: The system cannot find the file specified. (os error 2): readfile 'undefined' 
      at Object.readFile (ext:deno_fs/30_fs.js:747:24)
      at readFile (ext:deno_node/_fs/_fs_readFile.ts:29:14)
      at ext:deno_node/_fs/_fs_readFile.ts:44:5
      at new Promise (<anonymous>)
      at Module.readFilePromise (ext:deno_node/_fs/_fs_readFile.ts:43:10)
```
the root cause of this is that `deno info --json @std/encoding/base64` does not have a local field in the "modules" section, which causes the id field in the object returned by resolver.js:resolveDeno() to be undefined.

Is this a bug in this plugin or should `deno info --json` always return a local field in the modules section?

**Comment by bavoco** [comment]
BTW I'm fine with removing vendor: true from my deno.json if that makes this plugin work, but then I run into a different problem:

```
[vite] Internal server error: Failed to resolve import "./_validate_binary_like.ts" from "deno::TypeScript::@std/encoding/base64::C:/Users/my.username/AppData/Local/deno/remote/https/jsr.io/d0a47e8cc2cb0cb9991d5380e7bc290c496b680ff1b8a839bab0bc068c332477". Does the file exist?
  Plugin: vite:import-analysis
  File: deno::TypeScript::@std/encoding/base64::C:/Users/my.username/AppData/Local/deno/remote/https/jsr.io/d0a47e8cc2cb0cb9991d5380e7bc290c496b680ff1b8a839bab0bc068c332477:1:37
  1  |  import { validateBinaryLike } from "./_validate_binary_like.ts";
     |                                      ^
  2  |  const base64abc = [
  3  |    "A",
```

**Comment by amadsen** [comment]
> I ran in to this issue myself today. I have confirmed that the `"local"` property does not exist in the `deno info --json ${specifier}` output when `"vendor": true` is set and removing `"vendor": true` from `deno.json(c)` causes it to appear. Since `"vendor": true` indicates that non-npm packages will be cached in `./vendor` directory tree within the project folder, perhaps we can check for the existence / not-empty status of `mod.local` and, if it is not set, use `mod.specifier.replace(/^https:\/\//, './vendor/')` as a fallback.

It appears to work well locally for my project. I'll prepare a pull request.

**Comment by amadsen** [comment]
I'm having trouble figuring out how to test this. I'll leave the (one-line) diff here for now and come back to the PR when I have more time:

```
diff --git a/src/resolver.ts b/src/resolver.ts
index 3fbc645..d1fb152 100644
--- a/src/resolver.ts
+++ b/src/resolver.ts
@@ -119,7 +119,7 @@ export async function resolveDeno(
 
   if (mod.kind === "esm") {
     return {
-      id: mod.local,
+      id: mod.local || mod.specifier.replace(/http(s?):\/\//gi, './vendor/'),
       kind: mod.kind,
       loader: mod.mediaType,
       dependencies: mod.dependencies,
```
